### ISSUE TITLE
Collision in log fields

### ISSUE THREAD

**Issue by ColmanHumphrey** [LukeMathWalker/tracing-actix-web#1]
Hey Luca, 

Great crate!

One issue I noticed (working through your Zero2Prod book) is that we can have fields silently dropped in name collisions (also in email to you).

When using the following `tracing` macro within my lib code:

```rust
#[tracing::instrument(
    name = "Adding a new subscriber",
    skip(payload, pool),
    fields(
        request_id=%Uuid::new_v4(),
        email = %payload.email,
        name = %payload.name
    )
)]
```

This overwrites the `request_id` coming from within this crate, and we only see the one generated here. If I rename this one (to say `subscribe_request_id` or whatever) then the resulting logs have both fields.

Now in this specific example it may not make sense to have both, but I think there are cases were both would be relevant - and indeed any of the fields could be overwritten (I think).

I'm not 100% sure of the expected behaviour:
- An error could be raised on compilation
- Some form of name resolution could be put in place (so e.g. the interior `request_id` could become <function_name>_request_id etc)
- Warning on compilation

Hopefully I'm not speaking nonsense here

**Comment by LukeMathWalker** [comment]
Hey!
I have seen your email - I am planning to go through all the typos and little issues during next week :smile: 

This can indeed be tricky (i.e. I bumped into the very same issue in the book).
On possible solutions:

- There is no way to detect this at compilation time unfortunately;
- This is possible, but imo it would still be undesirable (the name of the field would be changed without you expecting it).

The only solution that comes to mind is adding a "warning" log in `tracing-bunyan-formatter` when there is a collision. Wdyt?

**Comment by ColmanHumphrey** [comment]
Oh I think that's pretty nice actually! With a flag to ignore this collision as a nice-to-have extra potentially.

- If this is easy for you, happy days!
- If I have time, potentially I can try help there, but indeed I will have to do a bunch of catch-up

Happy to close this issue (not sure if `tracing-bunyan-formatter` needs an issue for this?)

**Comment by LukeMathWalker** [comment]
If you open one on `tracing-bunyan-formatter` it makes it easier to track :+1:

**Comment by ColmanHumphrey** [comment]
Closing with https://github.com/LukeMathWalker/tracing-bunyan-formatter/issues/2 instead!
