### ISSUE TITLE
Span fields do not follow semantic conventions

### ISSUE THREAD

**Issue by lsunsi** [LukeMathWalker/tracing-actix-web#11]
Of course conventions are just that, conventions so not following them is not a issue on itself. In my use case, I want to use this library in production and I need the status_code of the span to be set a different way (following [otel conventions](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md)).

Are you open to a PR that would add this field at least (maybe others) as a config to the tracing logger?
I'd be willing to build something up as a suggestion. (:

**Comment by LukeMathWalker** [comment]
Hey!
I will soon have to release a new breaking change once `actix-web` pushes out `4.0.0`, so I am happy to consider additional breaking changes for bundling.

I am happy to align more closely with OTEL's convention - if you open a PR we can discuss the details 👍

**Comment by lsunsi** [comment]
I have a branch `bipa-app/span-fields-otel-conventions` which just renamed some fields to follow the convention, but I thought a PR just renaming stuff would not be good enough (because other people might follow other conventions and even want other fields). I took a crack at a more customizable approach, although I have some concerns for it as well. Anyway, we can talk it over on #13 (:

**Comment by LukeMathWalker** [comment]
The latest release, `0.4.0-beta.1`, aligns all field names with OpenTelemetry conventions. I'll close this one!
