### ISSUE TITLE
RootSpanBuilder customise http properties

### ISSUE THREAD

**Issue by kimdclvk** [LukeMathWalker/tracing-actix-web#110]
Ciao Luca!
thanks for providing this great library (and book!)
The requestId is great for us to be able to follow requests across workers.

It is also great that I can add domain specific fields, however I wasn't able to find a way to remove or customise existing http fields.
I ended up customising my http fields implementing `impl RootSpanBuilder` using `tracing::info_span!("Request", client_id)` which is far from ideal as I assume i'm losing all rootSpan goodies (Extractor to add custom properties).

It would be great if it could be also configured with a string pattern (ie: `%{http_method} %{http_ip_address} `).

Grazie!

**Comment by LukeMathWalker** [comment]
You can't tweak how existing properties are logged—you either define your own root span or take the existing way of logging them.
This is not something I plan to support.
