### ISSUE TITLE
[FEATURE] Add support for `v7` UUID in `RequestId`

### ISSUE THREAD

**Issue by NishantJoshi00** [LukeMathWalker/tracing-actix-web#115]
## Description

Currently, the request ID is generated using `v4`, which effectively addresses the common use-case of ensuring unique IDs within a specific range. However, when assessing use-cases that involve storing request IDs as sorting keys for analytics using `v4`, scalability becomes a concern. In contrast, `v7` offers a time-dependent prefix that facilitates the chronological sorting of requests, offering an additional advantage of enhancing locality.

## Implementation
- [x] I am willing to submit a PR

This change, however, introduces some added complexities:
- Currently, the [`uuid`](https://docs.rs/uuid/latest/uuid/) crate requires passing `unstable_uuid` as a configuration flag.
- This modification may conflict with any existing use cases in projects that use this crate. Therefore, it can be placed under an optional (non-default) feature flag.

**Comment by LukeMathWalker** [comment]
I'm open to the idea of adding it as an optional off-by-default feature, as long as we don't break semver.

**Comment by NishantJoshi00** [comment]
I agree, I don't consider it to be default feature either, as the current implementation of `uuid` contains caveats on enabling it.

**Comment by LukeMathWalker** [comment]
Implemented in #116.
