### ISSUE TITLE
Filtering tracing of http requests only that contain an error

### ISSUE THREAD

**Issue by jayvdb** [LukeMathWalker/tracing-actix-web#132]
I would to be able to run services at `RUST_LOG=error` and have only traces when there was an error during the request.

As far as I can see this isnt currently possible, as the trace level for the span needs to be set before the request starts, and typically the trace level at start is set to `info`.

My understanding is that the filters like `tracing_subscriber::EnvFilter::try_from_default_env()` see this http span trace set to `info` and if `RUST_LOG=error` they ignore any events that occur within the span even if they are error.

If I've understood that correct, then at least one way to approach this is to have a different root span builder that doesnt emit the span until the "end" when the status is known, and chooses a level based on the status of the request.

**Comment by jayvdb** [comment]
I get the feeling this cant be solved. The trace needs to start at the beginning of the request, and needs a level.

I am working around this by adding a `jq` filter to eliminate traces that does have an event at level `WARN` or `ERROR`

> jq '.resourceSpans[].scopeSpans[].spans[]|select(.events[].attributes[]|select(.key=="level" and (.value.stringValue=="ERROR" or .value.stringValue=="WARN")))'

**Comment by LukeMathWalker** [comment]
I confirm that this can't be solved given how `tracing` works.
