### ISSUE TITLE
Use the `request-id` header as the span request-id if present

### ISSUE THREAD

**Issue by moises-marquez** [LukeMathWalker/tracing-actix-web#30]
I might be missing something really obvious here, but I couldn't find anywhere in the documentation how to configure the middleware to use the `request-id` header for the span. 

I'm looking into this for distributed tracing.

**Comment by LukeMathWalker** [comment]
What do you mean by "overwriting"?

**Comment by moises-marquez** [comment]
The `request_id` used for the span is being generated by the tracing-actix-web, rather than using the `request-id` header already present.

**Comment by LukeMathWalker** [comment]
If your objective is to see all spans belonging to the same trace across services, you should be looking at `trace_id`.

**Comment by moises-marquez** [comment]
Indeed. Thanks, Luca!

I was doing tests initially with pseudo distributed tracing, and somewhat recalled seeing something in the docs to extract info from the incoming request, and what I was refering to was the `RootSpanBuilder` trait. 

This will help while I implement the distributed tracing properly.

Cheers!
