### ISSUE TITLE
HTTP status code cannot be u16

### ISSUE THREAD

**Issue by bobbymcr** [LukeMathWalker/tracing-actix-web#42]
RootSpanBuilder tries to record the HTTP status code as `u16`; see [here](https://github.com/LukeMathWalker/tracing-actix-web/blob/e1b272ec4c8f2009e1eafeac920ac52071c709b9/src/root_span_builder.rs#L48) and [here](https://github.com/LukeMathWalker/tracing-actix-web/blob/e1b272ec4c8f2009e1eafeac920ac52071c709b9/src/root_span_builder.rs#L67). However, this is not supported by OpenTelemetry. Per the protocol specification, only signed integer types are recognized; see [proto file](https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/common/v1/common.proto#L33).

The side effect of this is that the status code field is shipped as a string value over OTLP instead of an integer, causing some issues with downstream tooling. I believe an easy fix here is to change `u16` to `i16`.

**Comment by LukeMathWalker** [comment]
Thanks for noticing this - we could probably go down to `i16` as well without any issue.
