### ISSUE TITLE
Add HTTP Method to the span

### ISSUE THREAD

**Issue by ufoscout** [LukeMathWalker/tracing-actix-web#5]
At the moment only the request path (i.e. `req.path()`) is included in the span, anyway, I suppose the HTTP Method  (i.e. `req.method()`) should be included by default. What do you think, would it be possible to add it?

**Comment by LukeMathWalker** [comment]
Happy to add it!
Do you want to open a PR?

**Comment by lsunsi** [comment]
I took the liberty to open up a PR myself on this, since this issue seems to be inactive for a few months, hopefully it's okay!

**Comment by ufoscout** [comment]
@lsunsi Thanks! It's an extremely busy moment for me.
