### ISSUE TITLE
Support `actix-web` `4.0.0-beta.11`

### ISSUE THREAD

**Issue by caizixian** [LukeMathWalker/tracing-actix-web#52]
The new `actix-web` release supports using `#[tokio::main]`, which is quite nice.
https://twitter.com/algo_luca/status/1460533319234473987

At this moment, `tracing-actix-web``0.5.0-beta.1` pins the `actix-web` version, which makes sense for beta versions. It would be nice to have a new release that bumps the dependency version.

**Comment by LukeMathWalker** [comment]
Fixed in #54 (the irony of seeing your own tweet quoted 😅 )
