### ISSUE TITLE
Filter out actix state

### ISSUE THREAD

**Issue by 0xpr03** [LukeMathWalker/tracing-actix-web#56]
Currently when I have any kind of wrapped middleware or state it has to implement debug. Problem is that when you have some kind of secret (cookie key..) that you don't want to have logged, your only option is to implement Debug and simply not return anything.

**Comment by LukeMathWalker** [comment]
`tracing-actix-web` does not enforce any constraint on the state, in particular not `Debug`.
I'll close this for now - happy to look at it again if you provide a code sample showing the problem.

**Comment by 0xpr03** [comment]
Note: I was utilizing the #[instrument] macro from tracing to get function spans. The fix is to use [the skip fields option](https://docs.rs/tracing/0.1.29/tracing/attr.instrument.html#skipping-fields) So yeah, not really related to this library. It was just my first interaction with using the tracing things.
