### ISSUE TITLE
Configure the span logger level

### ISSUE THREAD

**Issue by ufoscout** [LukeMathWalker/tracing-actix-web#6]
At the moment the span logger level is hardcoded as `info_span!(...)`:
```rust
let span = tracing::info_span!(
            "Request",
            request_path = %req.path(),
            user_agent = %user_agent,
            client_ip_address = %req.connection_info().realip_remote_addr().unwrap_or(""),
            request_id = %Uuid::new_v4(),
            status_code = tracing::field::Empty,
        );
```
This makes the span not visible in our production environment where the logger level is set to `warn`.
Would it be possible to make it configurable somehow?

**Comment by LukeMathWalker** [comment]
Exposing the level as configuration would be a good improvement, I concur.

**Comment by msdrigg** [comment]
What outward facing api are you looking for on this? This is an issue I am interested in, but I don't know how you want this to be configured.
