### ISSUE TITLE
Feature request: HTTP Server-Timings header

### ISSUE THREAD

**Issue by joepio** [LukeMathWalker/tracing-actix-web#65]
Hi there! Thank you so much for creating and maintaining this. I've just added this to my atomic-server project and really love how much insights I can get from this.

I have one usecase in mind that I think could be interesting for others: the [HTTP Server-Timing header](https://www.w3.org/TR/server-timing/). This header allows clients to gain insight into which parts of a request take up most time. I find this very useful both in production as during development, as you can use your browser's built-in tools to get an idea of why a request might be slower than usual.

![Screenshot 2021-12-28 at 10 16 55](https://user-images.githubusercontent.com/2183313/147550357-d3dc78c3-1652-4c70-a593-43df78c7ca9c.png)

I've currently imlemented this header at the `handler` level, with some custom `Timing` struct, but I think it makes far more sense to use `Tracing` for this - it would allow me to share far deeper insights in this Header than I currently can.

I think this could be implemented as an optional Middleware. It would need access to the [RootSpan](https://docs.rs/tracing-actix-web/4.0.0-beta.1/tracing_actix_web/struct.RootSpan.html), I think, and it would need to iterate over it's children. 

This is what my current `Timer` looks like:

```rust
//! Monitor performance using HTTP headers
use std::time::Instant;

/// Timer used to share performance metrics to the client using the HTTP Server-Timing header
/// https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Server-Timing
pub struct Timer {
    last: Instant,
    timings: Vec<Timing>,
}

struct Timing {
    name: String,
    /// Time in milliseconds
    duration: u128,
}

impl Timer {
    pub fn new() -> Self {
        Timer {
            last: Instant::now(),
            timings: Vec::new(),
        }
    }

    /// Adds a named measurement, counting from the last one
    pub fn add(&mut self, name: &str) {
        let now = Instant::now();
        let duration = now.duration_since(self.last).as_millis();
        self.last = now;
        self.timings.push(Timing {
            name: name.into(),
            duration,
        });
    }

    /// Returns the value for a Server-Timings header.
    /// https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Server-Timing
    pub fn to_header(&self) -> String {
        let mut out = String::new();
        for timing in self.timings.iter() {
            out.push_str(&format!("{};dur={}, ", timing.name, timing.duration));
        }
        out
    }
}
```

## Nesting / Grouping

The Server-Timing header does not have nesting / grouping, and names have to be unique. This differs from Spans in Tracing, of course. We can deal with this in (at least) two ways: 

1) we only go one span deep. This would mean some insights will be lost.
1) we create longer names for nested spans (e.g. `level1name-level2name`). This will lead to a more complete, but harder to understand timings header.
1) leave it up to the one using the middleware, add an option for allowed depth.

@LukeMathWalker I'd love to hear your thoughts about this. Is this relevant for this library? I haven't created an actix middleware yet, but I might be willing to take a go at this.

**Comment by LukeMathWalker** [comment]
Hey!

I am not interested in supporting this functionality in `tracing-actix-web` - while I can see the appeal, it introduces a lot of complexity and the value of the insights quickly diminishes if you are not using a monolithic backend. It also increases considerably the size of the response while leaking details about the internals of the service, which I strongly advise against in a production deployment.  
My suggestion would be to return the trace identifier and use that to query the tracing data from a specialised service (e.g. Honeycomb/Jaeger/etc.)/require the API client to submit that when having issues with a specific request..

If you really want to push this forward in your own project/as a separate crate, I can offer some suggestions:   

- Even though you can get access to the `Span` wrapped inside `RootSpan`, this will not allow you to iterate over its children. To get access to those APIs you need to implement a custom `tracing` `Layer` or `Subscriber` - you can look into `tracing-bunyan-formatter` to get an idea of what that looks like;
- You can use some "special" fields to mark the root span (by using the `root_span!` macro) which can then be intercepted by your custom layer to know where to start tracking the server timings. You can look at the `tracing-opentelemetry` crate for inspiration;
- You can then provide an extension method over `Span` that returns the `Server-Timing` header. You can look again at `tracing-opentelemetry` for [inspiration](https://github.com/tokio-rs/tracing/blob/master/tracing-opentelemetry/src/span_ext.rs). You will probably need something similar to their collector to be able to access the stored information from outside the layer.

**Comment by joepio** [comment]
Thank you for your insights!
