### ISSUE TITLE
Emit a response header for the request ID

### ISSUE THREAD

**Issue by barbu110** [LukeMathWalker/tracing-actix-web#80]
Hi, 

I would like to be able to emit a response header containing the generated request ID. I believe we should be able to specify the name of the header and have the rest done automatically. Also, I think this should be an opt-in feature of the crate.

I am willing to put together a PR if this is something you'd like to add to the project.

P.S. Amazing work!

**Comment by LukeMathWalker** [comment]
Hey!
This is not a feature I want to add to the crate, but you should be able to build your own middleware to accomplish it - you need to extract the current request id and inject the relevant header :)
