### ISSUE TITLE
Compatibility with sentry-tracing

### ISSUE THREAD

**Issue by swarkentin** [LukeMathWalker/tracing-actix-web#81]
Hi there,

First of all - thank you very much for your libraries and contributions on your blog -- [Are we observable yet?](https://www.lpalmieri.com/posts/2020-09-27-zero-to-production-4-are-we-observable-yet/) is fantastic!

I have tried integrating `tracing-actix-web` with a [`sentry-tracing`](https://github.com/getsentry/sentry-rust/tree/master/sentry-tracing) but cannot seem to get sentry to group spans with the `RootSpan` provided with `TracingLogger`.

I have tried vanilla `instrument` methods:

```rust
/// Route handler to get things
#[tracing::instrument(skip(dao, identity))]
async fn get_all_the_things(
    dao: Data<Dao>,
    identity: Identity,
) ->  {
```

Or setting the parent to `RootSpan` in `instrument`:

```rust
/// Route handler to get things
#[tracing::instrument(parent = root_span, skip(dao, identity))]
async fn get_all_the_things(
    dao: Data<Dao>,
    identity: Identity,
    root_span: RootSpan
) ->  {
```

And even tried inside a `FromRequest` Extractor:

```rust
impl FromRequest for Foo {

    #[tracing::instrument(parent = req.extensions().get::<RootSpan>().cloned().unwrap().deref(), skip_all)]
    fn from_request(req: &HttpRequest, _: &mut Payload) -> Self::Future {
       // Do something inside of the RootSpan
    }
``` 

But nothing I do seems to group together methods marked with `#[tracing:instrument]` when viewed in Sentry. I only ever see one Event for each request (created by `RootSpan` in `TracingLogger`). Never any other events that happen in the context of that request.

`sentry-tracing` DOES upload events/spans for any method marked with `#[tracing:instrument]` -- but it does so without tying things together across a Request.

Do you have any ideas for how to group together all instrumented events under a Request to work with `sentry-tracing` -- or do you think this is something that should be resolved on the `sentry-tracing` `Layer`?

**Comment by LukeMathWalker** [comment]
Hi!

I think this is an issue that should be reported on the repository for Sentry's tracing subscriber. I am unfortunately unfamiliar with the way their export works, in particular what they use for correlation 😞

**Comment by swarkentin** [comment]
> Hi!
> 
> I think this is an issue that should be reported on the repository for Sentry's tracing subscriber. I am unfortunately unfamiliar with the way their export works, in particular what they use for correlation 😞

No problem -- thank you for the response!
