### ISSUE TITLE
Is it possible to remove some of the default fields from the root span builder?

### ISSUE THREAD

**Issue by stefan-vatov** [LukeMathWalker/tracing-actix-web#83]
Hi there,

Awesome job with this library and the book as well, it helps a ton!

I have a question regarding the root span macro and builder. The default span (and the macro) adds a bunch of fields, most of them beneficial, but things like `http.client_ip` and the IP could go into GDPR territory. After some looking around in the code, I came up on the `root_span!` macro and the root span builder. In the example, in the repo, you add fields to the root span but don't remove any.

Building a custom root span and passing in `http.client_ip` with `x` works in overriding, but it doesn't remove the field. Also, if there is something that's not supposed to be in the logs in the headers, not sure how that could be removed.

**Comment by LukeMathWalker** [comment]
This is currently not possible nor, unfortunately, easily achievable. You already spotted the workaround I was going to suggest - set the "offending" field to a dummy value.
Another option is to filter the attribute out in your tracing subscriber.

> Also, if there is something that's not supposed to be in the logs in the headers, not sure how that could be removed.

I am not sure I follow here. What are you referring to precisely?

**Comment by stefan-vatov** [comment]
Thanks for the quick reply!

The dummy values work. I think I'll go with that as the workaround.

>Another option is to filter the attribute out in your tracing subscriber.

Do you have any examples on this one? Tried filtering, but doesn't that filter out the whole span for the layer? Maybe I'm getting confused here, but when I tried it out, I didn't find a way to filter out specific fields but instead the whole span for the layer.

>I am not sure I follow here. What are you referring to precisely?

In the logs, it ends up logging _all_ the request headers (prints out the whole struct I suspect), which includes any sensitive fields picked out in the root span builder from the headers :)

**Comment by LukeMathWalker** [comment]
> Do you have any examples on this one? Tried filtering, but doesn't that filter out the whole span for the layer? Maybe I'm getting confused here, but when I tried it out, I didn't find a way to filter out specific fields but instead the whole span for the layer.

You need to write a custom layer, nothing is available out of the box in the ecosystem with this capability (skipping fields) as far as I know. But it's definitely possible.

> In the logs, it ends up logging _all_ the request headers (prints out the whole struct I suspect), which includes any sensitive fields picked out in the root span builder from the headers :)

I don't think that's the case - see https://github.com/LukeMathWalker/tracing-actix-web/blob/973d9b03898a3c4691ef9307cfc324147d3c1e62/src/root_span_macro.rs#L78
Can you provide a small reproducible example where you see this coming out of `tracing-actix-web`?
