### ISSUE TITLE
Sending tracing context to other actors

### ISSUE THREAD

**Issue by kesavkolla** [LukeMathWalker/tracing-actix-web#87]
I have different actix actors doing different activities. From the web request I invoke the actor doing the processing. Is there any way to send the context that tracing-actix-web setup to other actors? There is tracing-actix crate which does the instrumentation of actors. Is there any way to combine these two features?

**Comment by LukeMathWalker** [comment]
I have never worked with the `actix` actor framework, but I think the simplest solution is to get the current span via `Span::current()` and then pass it to the actor.
